config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :subjects
  resources :faculties
  resources :branches
  get 'home/index'
  devise_for :users
  root 'landing_page#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
# frozen_string_literal: true

class Branch < ApplicationRecord
  has_many :subjects
  has_many :faculties
end

app/models/faculty.rb
# frozen_string_literal: true

class Faculty < ApplicationRecord
  belongs_to :subject
  belongs_to :branch
end

app/models/subject.rb
# frozen_string_literal: true

class Subject < ApplicationRecord
  has_one :faculty
  belongs_to :branch
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: [:edit, :update, :destroy]

  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all
  end



  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to branches_url, notice: 'Branch was successfully created.' }
        format.json { render :index, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def branch_params
      params.require(:branch).permit(:name, :alias)
    end
end

app/controllers/faculties_controller.rb
# frozen_string_literal: true

class FacultiesController < ApplicationController
  before_action :set_faculty, only: %i[edit update destroy]
  before_action :set_branch, only: %i[edit new index create]
  before_action :set_subject, only: %i[edit new index create]

  # GET /faculties
  # GET /faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit; end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to faculties_url, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to faculties_url, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: faculties_url }
      else
        format.html { render :edit }
        format.json { render json: faculties_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_faculty
    @faculty = Faculty.find(params[:id])
  end

  def set_branch
    @branch = Branch.all
  end

  def set_subject
    @subject = Subject.all
  end

  # Only allow a list of trusted parameters through.
  def faculty_params
    params.require(:faculty).permit(:name, :alias, :branch_id, :subject_id)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @branches = Branch.all
    @branch = Branch.all
    @subjects = Subject.all
    @faculties = Faculty.all
  end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/controllers/subjects_controller.rb
# frozen_string_literal: true

class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[edit update destroy]
  before_action :set_branch, only: %i[edit new index create]
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit; end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subjects_url, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to subjects_url, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subject
    @subject = Subject.find(params[:id])
  end

  def set_branch
    @branch = Branch.all
  end

  # Only allow a list of trusted parameters through.
  def subject_params
    params.require(:subject).permit(:name, :alias, :branch_id, :semester)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/branches/_branch.html.erb
<table class="table table-hover table-responsive-sm">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Alias</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @branches.each do |branch| %>
      <tr>
        <td><%= branch.name %></td>
        <td><%= branch.alias %></td>
        <td><%= link_to '', edit_branch_path(branch), class:"fa fa-pencil-square-o fa-lg" %></td>
        <td><%= link_to '', branch, method: :delete, data: { confirm: 'Are you sure?' }, class:"fa fa-trash fa-lg" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/branches/_form.html.erb
<%= form_with(model: branch, local: true) do |form| %>
  <% if branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(branch.errors.count, "error") %> prohibited this branch from being saved:</h2>
      <ul>
        <% branch.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control shadow rounded"%>
  </div>
  <div class="form-group">
    <%= form.label :alias %>
    <%= form.text_field :alias, class:"form-control shadow rounded" %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h1>Editing Branch</h1>

<%= render 'form', branch: @branch %>

<%= link_to 'Back', branches_path %>

app/views/branches/index.html.erb
<h1>Branches</h1>
<% if @branches.count > 0 %>
  <%= render 'branch' %>
<% else %>
  <h4>No Subject entered</h4>
<% end %>
<br>
<%= link_to 'New Branch', new_branch_path %>

app/views/branches/new.html.erb
<h1>New Branch</h1>

<%= render 'form', branch: @branch %>

<%= link_to 'Back', branches_path %>

app/views/faculties/_faculty.html.erb
<table class="table table-hover table-responsive-sm">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Alias</th>
      <th scope="col">Branch</th>
      <th scope="col">Subject</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @faculties.each do |faculty| %>
      <tr>
        <td><%= faculty.name %></td>
        <td><%= faculty.alias %></td>
        <td><%= faculty.branch.alias %></td>
        <td><%= faculty.subject.alias %></td>
        <td><%= link_to '', edit_faculty_path(faculty),class:"fa fa-pencil-square-o fa-lg" %></td>
        <td><%= link_to '', faculty, method: :delete, data: { confirm: 'Are you sure?' }, class:"fa fa-trash fa-lg" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/faculties/_form.html.erb
<%= form_with(model: faculty, local: true) do |form| %>
  <% if faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>
      <ul>
        <% faculty.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control shadow rounded" %>
  </div>
  <div class="form-group">
    <%= form.label :alias %>
    <%= form.text_field :alias, class:"form-control shadow rounded" %>
  </div>
  <div class="form-group">
    <%= form.label :branch_id, class: ""  %>
    <%= form.select(:branch_id) do %>
      <% @branch.each do |b| -%>
        <%= content_tag(:option, b.name, value: b.id) %>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <%= form.label :subject_id, class: ""  %>
    <%= form.select(:subject_id) do %>
      <% @subject.each do |sub| -%>
        <%= content_tag(:option, sub.name, value: sub.id) %>
      <% end %>
    <% end %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<h1>Editing Faculty</h1>

<%= render 'form', faculty: @faculty %>


<%= link_to 'Back', faculties_path %>

app/views/faculties/index.html.erb
<h1>Faculties</h1>
<% if @faculties.count > 0 %>
  <%= render 'faculty' %>
<% else %>
  <h4>No Subject entered</h4>
<% end %>
<br>
<%= link_to 'New Faculty', new_faculty_path %>

app/views/faculties/new.html.erb
<h1>New Faculty</h1>
<% if (@branch.present?) && (@subject.present?) %>
  <%= render 'form', faculty: @faculty %>
<% elsif (@subject.present?) %>
  <h4>Your Department table is empty, first add <%= link_to 'Department', new_branch_path%> here</h4>
<% elsif (@branch.present?) %>
  <h4>Your Subjects table is empty, first add <%= link_to 'Subjects', new_subject_path%> here</h4>
<% else %>
  <h4>Your Department and Subject tables are empty add both from here <%= link_to 'Department', new_branch_path%> and <%= link_to 'Subjects', new_subject_path%></h4>
<% end %>
<%= link_to 'Back', faculties_path %>

app/views/home/index.html.erb
<h1>Department</h1>
<% if @branches.count > 0 %>
  <%= render 'branches/branch' %>
<% else %>
  <h4>No Subject entered</h4>
<% end %>
<hr style="height:2px;border-width:0;color:gray;background-color:gray">
<h1>Faculties</h1>
<% if @faculties.count > 0 %>
  <%= render 'faculties/faculty' %>
<% else %>
  <h4>No Subject entered</h4>
<% end %>
<hr style="height:2px;border-width:0;color:gray;background-color:gray">
<h1>Subjects</h1>
<% if @subjects.count > 0 %>
  <%= render 'subjects/subject' %>
<% else %>
  <h4>No Subject entered</h4>
<% end %>
<br style="height:2px;border-width:0;color:gray;background-color:gray">

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <% if !user_signed_in? %>
      <%= link_to 'Timetable Generator', root_path, class:"navbar-brand"%>
    <% else %>
      <%= link_to 'Timetable Generator', home_index_path, class:"navbar-brand"%>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'Home', home_index_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Resources
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'Department', branches_path, class:"dropdown-item"%>
            <%= link_to 'Faculties', faculties_path, class:"dropdown-item"%>
            <%= link_to 'Subjects', subjects_path, class:"dropdown-item"%>
          </div>
        </li>
        <% if !user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Log in', new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Log out', destroy_user_session_path, class:"nav-link" , method: :delete %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeTableGenerator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
    </div>
    <% unless current_page?(root_path) %>
      <div class="container">
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>
      <ul>
        <% subject.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control shadow rounded" %>
  </div>
  <div class="form-group">
    <%= form.label :alias %>
    <%= form.text_field :alias, class:"form-control shadow rounded" %>
  </div>
  <div class="form-group">
    <%= form.label :branch_id, class: ""  %>
    <%= form.select(:branch_id) do %>
      <% @branch.each do |b| -%>
        <%= content_tag(:option, b.name, value: b.id) %>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <%= form.label :semester %>
    <%= form.select :semester,(1..8) ,class:"form-control dropdown shadow rounded" %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/_subject.html.erb
<table class="table table-hover table-responsive-sm">
    <thead class="thead-light">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Alias</th>
        <th scope="col">Branch</th>
        <th scope="col">Semester</th>
        <th colspan="3">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @subjects.each do |subject| %>
        <tr>
          <td><%= subject.name %></td>
          <td><%= subject.alias %></td>
          <td><%= subject.branch.alias %></td>
          <td><%= subject.semester %></td>
          <td><%= link_to '', edit_subject_path(subject), class:"fa fa-pencil-square-o fa-lg" %></td>
          <td><%= link_to '', subject, method: :delete, data: { confirm: 'Are you sure?' }, class:"fa fa-trash fa-lg", class:"fa fa-trash fa-lg"%></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<h1>Subjects</h1>
<% if @subjects.count > 0 %>
  <%= render 'subject' %>
<% else %>
  <h4>No Subject entered</h4>
<% end %>
<br>
<%= link_to 'Add New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>Add New Subject</h1>
<% if (@branch.present?) %>
  <%= render 'form', subject: @subject %>
<% else %>
  <h4>Your Department table is empty, first add <%= link_to 'Department', branches_path%> here</h4>
  <br>
<% end %>
<%= link_to 'Back', subjects_path %>